export const {
  NEXT_PUBLIC_APPWRITE_ENDPOINT,
  NEXT_PUBLIC_APPWRITE_PROJECT: PROJECT_ID,
  NEXT_PUBLIC_APPWRITE_BUCKET: BUCKET_ID,
  APPWRITE_DATABASE: DATABASE_ID,
  APPWRITE_USERS_COLLECTION: USERS_COLLECTION_ID,
  APPWRITE_CHATS_COLLECTION: CHATS_COLLECTION_ID,
  APPWRITE_MESSAGES_COLLECTION: MESSAGES_COLLECTION_ID,
  APPWRITE_API_KEY: APPWRITE_SECRET_KEY,
} = process.env;
